load("@prelude-si//:macros.bzl", "rust_library")

rust_library(
    name = "council-core",
    deps = [
        "//lib/si-data-nats:si-data-nats",
        "//lib/telemetry-rs:telemetry",
        "//third-party/rust:remain",
        "//third-party/rust:serde",
        "//third-party/rust:strum",
        "//third-party/rust:ulid",
    ],
    srcs = glob(["src/**/*.rs"]),
)
